export const suggestedQuestions = [
  "What is the concept of justice?",
  "How does the legal system ensure fairness?",
  "What are human rights?",
  "Can you explain the role of a judge?",
  "What is the difference between civil and criminal law?",
  "How is a legal precedent set?",
  "What are the main sources of law?",
  "Can you explain the concept of legal ethics?",
  "What is the role of a prosecutor?",
  "What is the structure of the Indian judiciary?",
  "How is the Supreme Court of India organized?",
  "What are the powers of the Chief Justice of India?",
  "What is the role of High Courts in India?",
  "How do District Courts function in India?",
  "What is the process of appointment for judges in India?",
  "What are the qualifications required to be a judge in India?",
  "Can you explain the role of the Attorney General of India?",
  "What is the National Judicial Data Grid?",
  "How does the Indian legal system handle constitutional matters?",
  "What are the functions of the Indian Law Commission?",
  "How does the Indian judicial system address public interest litigation?",
  "What is the role of the Lok Sabha in shaping Indian justice?",
  "How does the Rajya Sabha influence the legal system in India?",
  "What is the process for filing a writ petition in India?",
  "Can you explain the concept of judicial review in India?",
  "What are the major legal reforms in India in the past decade?",
  "How does the Indian legal system handle corruption cases?",
  "What are the key principles of the Indian Penal Code?",
  "How is justice administered in cases of human trafficking in India?",
  "What are the landmark judgments of the Supreme Court of India?",
  "What is the role of the National Human Rights Commission in India?",
  "How does the Indian judiciary protect minority rights?",
  "What are the legal protections for women in India?",
  "How does the Indian legal system address child rights?",
  "What is the procedure for appeal in Indian courts?",
  "How does the Indian legal system handle environmental justice?",
  "What are the laws governing freedom of speech in India?",
  "How does India address issues of social justice through its legal system?",
  "What is the role of legal aid in India?",
  "Can you explain the concept of 'anticipatory bail' in Indian law?",
  "How does the Indian judiciary deal with cases of wrongful detention?",
  "What are the laws related to cybercrime in India?",
  "How does the Indian legal system address caste-based discrimination?",
  "What is the procedure for amending the Constitution of India?",
  "How does India handle disputes related to property rights?",
  "What are the laws governing marriage and divorce in India?",
  "How does the legal system in India address domestic violence?",
  "What are the rights of accused persons in Indian law?",
  "Can you explain the role of the Central Bureau of Investigation (CBI) in India?",
  "How does the Indian judiciary handle cases of economic offenses?",
  "What are the legal provisions for protecting intellectual property in India?",
  "How does the Indian legal system address issues of land acquisition?",
  "What are the rights of prisoners under Indian law?",
  "How does the Indian legal system handle cases of terrorism?",
  "What is the role of the National Commission for Scheduled Castes?",
  "How does the Indian judiciary ensure the right to a fair trial?",
  "What are the laws related to consumer protection in India?",
  "How does the Indian legal system handle disputes involving foreign nationals?",
  "What is the role of the State Human Rights Commissions?",
  "How does the Indian judiciary address the issue of corruption in public offices?",
  "What are the legal procedures for dealing with illegal migration in India?",
  "Can you explain the process of judicial activism in India?",
  "What are the key aspects of the Indian Evidence Act?",
  "How does the Indian judiciary handle cases of hate speech?",
  "What are the roles and responsibilities of the National Commission for Women?",
  "How does India address the issue of child labor through its legal system?",
  "What are the laws governing freedom of religion in India?",
  "How does the Indian judiciary deal with issues of national security?",
  "What are the key principles of the Indian Constitution related to justice?",
  "How does the Indian legal system address issues of poverty and inequality?",
  "What is the process for initiating a public interest litigation in India?",
  "How does the Indian judiciary handle cases of environmental degradation?",
  "What are the legal provisions for ensuring access to education in India?",
  "How does the Indian legal system address cases of medical negligence?",
  "What are the major challenges faced by the Indian judiciary?",
  "How does the Indian legal system address issues of juvenile justice?",
  "What is the role of the Election Commission of India in maintaining legal integrity?",
  "How does the Indian judiciary handle disputes related to intellectual property?",
  "What are the legal provisions for protecting the rights of persons with disabilities in India?",
  "How does the Indian legal system address issues of workplace harassment?",
  "What is the process for handling complaints against judges in India?",
  "How does the Indian judiciary ensure transparency and accountability?",
  "What are the key aspects of the Right to Information Act in India?",
  "How does the Indian legal system address issues of religious intolerance?",
  "What are the legal provisions for protecting consumer rights in India?",
  "How does the Indian judiciary handle cases of cross-border disputes?",
  "What is the role of the Supreme Court in shaping public policy in India?",
  "How does the Indian legal system deal with cases of electoral fraud?",
  "What are the legal measures for protecting cultural heritage in India?",
  "How does the Indian judiciary address issues related to animal rights?",
  "What are the laws related to housing and urban development in India?",
  "How does the Indian legal system address issues of drug trafficking?",
  "What is the process for challenging a legislative act in India?",
  "How does the Indian judiciary handle issues of social justice and inclusion?",
  // New questions related to keywords
  "What is the role of the National Judicial Data Grid in improving judicial efficiency?",
  "How does the Indian Constitution address the concept of social justice?",
  "What are the key provisions of the Right to Information Act in India?",
  "How does the Indian legal system handle cases of cybercrime?",
  "What is the process for filing a Public Interest Litigation (PIL) in India?",

  // 100 new questions about Indian and global justice
  "How does the Indian judiciary balance individual rights with national security concerns?",
  "What are the key differences between the Indian legal system and the common law system?",
  "How does India's anti-corruption legislation compare to global standards?",
  "What role does the Law Commission of India play in legal reforms?",
  "How does India's juvenile justice system work, and how has it evolved over time?",
  "What are the challenges in implementing environmental laws in India?",
  "How does India's legal system address issues of data privacy and protection?",
  "What is the role of Alternative Dispute Resolution (ADR) in the Indian justice system?",
  "How does India's legal aid system function, and what are its challenges?",
  "What are the key features of India's anti-trafficking laws?",
  "How does India's legal system address issues of religious freedom and secularism?",
  "What are the legal provisions for protecting whistleblowers in India?",
  "How does India's legal system handle cases of honor killings?",
  "What are the challenges in implementing laws against manual scavenging in India?",
  "How does India's legal system address issues of food security and the right to food?",
  "What are the legal provisions for protecting senior citizens in India?",
  "How does India's legal system address issues of tribal rights and forest conservation?",
  "What are the key features of India's laws on surrogacy and assisted reproductive technologies?",
  "How does India's legal system handle cases of corporate fraud?",
  "What are the legal provisions for protecting street vendors in India?",
  "How does India's legal system address issues of digital surveillance and privacy?",
  "What are the key features of India's laws on organ transplantation?",
  "How does India's legal system handle cases of medical malpractice?",
  "What are the legal provisions for protecting LGBTQ+ rights in India?",
  "How does India's legal system address issues of fake news and misinformation?",
  "What are the key features of India's laws on artificial intelligence and robotics?",
  "How does India's legal system handle cases of mob lynching?",
  "What are the legal provisions for protecting the rights of persons with mental illness in India?",
  "How does India's legal system address issues of urban poverty and homelessness?",
  "What are the key features of India's laws on cryptocurrency and blockchain?",
  "How does India's legal system handle cases of child sexual abuse?",
  "What are the legal provisions for protecting the rights of intersex individuals in India?",
  "How does India's legal system address issues of water pollution and water rights?",
  "What are the key features of India's laws on euthanasia and the right to die with dignity?",
  "How does India's legal system handle cases of cross-border terrorism?",
  "What are the legal provisions for protecting the rights of HIV-positive individuals in India?",
  "How does India's legal system address issues of caste-based violence?",
  "What are the key features of India's laws on space exploration and satellite technology?",
  "How does India's legal system handle cases of online harassment and cyberbullying?",
  "What are the legal provisions for protecting the rights of sex workers in India?",
  "How does India's legal system address issues of genetically modified organisms and food safety?",
  "What are the key features of India's laws on adoption and foster care?",
  "How does India's legal system handle cases of sedition and free speech?",
  "What are the legal provisions for protecting the rights of religious minorities in India?",
  "How does India's legal system address issues of climate change and environmental refugees?",
  "What are the key features of India's laws on drone technology and aerial surveillance?",
  "How does India's legal system handle cases of honor violence against women?",
  "What are the legal provisions for protecting the rights of migrant workers in India?",
  "How does India's legal system address issues of digital identity and biometric data protection?",
  "What are the key features of India's laws on wildlife conservation and biodiversity?",
  "How does India's legal system handle cases of custodial torture and police brutality?",
  "What are the legal provisions for protecting the rights of differently-abled students in India?",
  "How does India's legal system address issues of urban air pollution and public health?",
  "What are the key features of India's laws on stem cell research and gene editing?",
  "How does India's legal system handle cases of electoral malpractices and booth capturing?",
  "What are the legal provisions for protecting the rights of indigenous knowledge and traditional medicine in India?",
  "How does India's legal system address issues of nuclear energy and radiation safety?",
  "What are the key features of India's laws on witness protection?",
  "How does India's legal system handle cases of forced religious conversion?",
  "What are the legal provisions for protecting the rights of prisoners on death row in India?",
  "How does India's legal system address issues of sustainable development and green economy?",
  "What are the key features of India's laws on facial recognition technology and privacy?",
  "How does India's legal system handle cases of acid attacks?",
  "What are the legal provisions for protecting the rights of third-gender individuals in India?",
  "How does India's legal system address issues of agricultural distress and farmer suicides?",
  "What are the key features of India's laws on autonomous vehicles and liability?",
  "How does India's legal system handle cases of workplace discrimination?",
  "What are the legal provisions for protecting the rights of refugees and asylum seekers in India?",
  "How does India's legal system address issues of digital currency and financial technology?",
  "What are the key features of India's laws on animal welfare and prevention of cruelty?",
  "How does India's legal system handle cases of fake encounters and extrajudicial killings?",
  "What are the legal provisions for protecting the rights of persons with rare diseases in India?",
  "How does India's legal system address issues of maritime security and piracy?",
  "What are the key features of India's laws on nanotechnology and its applications?",
  "How does India's legal system handle cases of child marriage?",
  "What are the legal provisions for protecting the rights of linguistic minorities in India?",
  "How does India's legal system address issues of noise pollution in urban areas?",
  "What are the key features of India's laws on virtual and augmented reality?",
  "How does India's legal system handle cases of human organ trafficking?",
  "What are the legal provisions for protecting the rights of sanitation workers in India?",
  "How does India's legal system address issues of digital divide and internet access?",
  "What are the key features of India's laws on international child abduction?",
  "How does India's legal system handle cases of corporate environmental crimes?",
  "What are the legal provisions for protecting the rights of victims of communal violence in India?",
  "How does India's legal system address issues of sports law and doping?",
  "What are the key features of India's laws on artificial wombs and reproductive rights?",
  "How does India's legal system handle cases of land grabbing and forced evictions?",
  "What are the legal provisions for protecting the rights of elderly prisoners in India?",
  "How does India's legal system address issues of biopiracy and traditional knowledge?",
  "What are the key features of India's laws on brain-computer interfaces and neuroethics?",
  "How does India's legal system handle cases of online gambling and addiction?",
  "What are the legal provisions for protecting the rights of victims of human trafficking in India?",
  "How does India's legal system address issues of space debris and satellite collisions?",
  "What are the key features of India's laws on quantum computing and cryptography?",
  "How does India's legal system handle cases of honor killing within the LGBTQ+ community?",
  "What are the legal provisions for protecting the rights of community health workers in India?",
  "How does India's legal system address issues of deep fake technology and digital manipulation?",
  "What are the key features of India's laws on geoengineering and climate modification?",
  "How does India's legal system handle cases of caste-based discrimination in the private sector?",
  "What are the legal provisions for protecting the rights of surrogate mothers in India?",
];
